spring.application.name=wateria
spring.datasource.url=jdbc:mysql://my-app-db.ckt44gq4yoai.us-east-1.rds.amazonaws.com:3306/myappdb
spring.datasource.username=admin
spring.datasource.password=7892327392Gg!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect